General:
  Measurement: "CMS_ttbar"
  POI: "zprimett4000_norm"
  HistogramFolder: "histograms"
  InputPath: "histograms_merged.root:{RegionPath}_{SamplePath}{VariationPath}"
  VariationPath: "_nominal"
  
Regions:
  - Name: "4j1b CR"
    RegionPath: "4j1b"
    Variable: "$H_T$ [GeV]"
    Binning: [50, 70, 90, 110, 130, 150, 170, 190, 210, 230, 250, 270, 290, 310, 330, 350, 370, 390, 410, 430, 450, 470, 490, 510, 530, 550]
  - Name: "4j2b SR"
    RegionPath: "4j2b"
    Variable: "$m_{bjj}$ [GeV]"
    Binning: [50, 70, 90, 110, 130, 150, 170, 190, 210, 230, 250, 270, 290, 310, 330, 350, 370, 390, 410, 430, 450, 470, 490, 510, 530, 550]

Samples:
  - Name: "Pseudodata"
    SamplePath: "pseudodata"
    Data: True

  - Name: "ttbar"
    SamplePath: "ttbar"

  - Name: "W+jets"
    SamplePath: "wjets"

  - Name: "single top, s-channel"
    SamplePath: "single_top_s_chan"

  - Name: "single top, t-channel"
    SamplePath: "single_top_t_chan"

  - Name: "tW"
    SamplePath: "single_top_tW"

  - Name: "zprimett4000"
    SamplePath: "zprimett4000"

Systematics:
  - Name: "ME variation"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_ME_var"
    Down:
      Symmetrize: True
    Samples: "ttbar"

  - Name: "PS variation"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_PS_var"
    Down:
      Symmetrize: True
    Samples: "ttbar"

  - Name: "ttbar scale variations"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_scaleup"
    Down:
      VariationPath: "_scaledown"
    Samples: "ttbar"

  - Name: "Jet energy scale"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_pt_scale_up"
    Down:
      Symmetrize: True

  - Name: "Jet energy resolution"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_pt_res_up"
    Down:
      Symmetrize: True

  - Name: "b-tag NP 1"
    Type: "NormPlusShape"
    Up:   { VariationPath: "_btag_var_0_up" }
    Down: { VariationPath: "_btag_var_0_down" }
    Samples: ["ttbar", "W+jets", "single top, s-channel", "single top, t-channel", "tW"]

  - Name: "b-tag NP 2"
    Type: "NormPlusShape"
    Up:   { VariationPath: "_btag_var_1_up" }
    Down: { VariationPath: "_btag_var_1_down" }
    Samples: ["ttbar", "W+jets", "single top, s-channel", "single top, t-channel", "tW"]

  - Name: "b-tag NP 3"
    Type: "NormPlusShape"
    Up:   { VariationPath: "_btag_var_2_up" }
    Down: { VariationPath: "_btag_var_2_down" }
    Samples: ["ttbar", "W+jets", "single top, s-channel", "single top, t-channel", "tW"]

  - Name: "b-tag NP 4"
    Type: "NormPlusShape"
    Up:   { VariationPath: "_btag_var_3_up" }
    Down: { VariationPath: "_btag_var_3_down" }
    Samples: ["ttbar", "W+jets", "single top, s-channel", "single top, t-channel", "tW"]

  - Name: "W+jets scale variations"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_scale_var_up"
    Down:
      VariationPath: "_scale_var_down"
    Samples: "W+jets"

  - Name: "Luminosity"
    Type: "Normalization"
    Up:
      Normalization: 0.03
    Down:
      Normalization: -0.03

NormFactors:
  - Name: "ttbar_norm"
    Samples: "ttbar"
    Nominal: 1.0
    Bounds: [0, 10]

  - Name: "zprimett4000_norm"
    Samples: "zprimett4000"
    Nominal: 1.0
    Bounds: [0, 50]
